name: build

on:
  push:
    branches: [main]
    paths:
      - src/**
      - '*.json'
      - .github/workflows/build.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - '*.json'
      - .github/workflows/build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn build
      - run: yarn package
      - uses: ./.github/actions/update-generated-files
